In [27]:
from  sklearn  import  datasets

In [28]:
# checking all datasets 
#dir(datasets)

In [29]:
# only importing  iris data 
from sklearn.datasets  import load_iris
iris=load_iris()

In [30]:
#  now des 
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [31]:
#  checking  descr 
#iris.DESCR
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [32]:
features_data=iris.data

In [33]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [34]:
label_data=iris.target

In [35]:
label_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [36]:
train_data1=features_data[0:49]

In [37]:
testing_data=label_data[0::50]

In [38]:
import numpy  as np


In [39]:
#  this approach will be  done by black sheersha

In [40]:
# to split training and testing  data
from  sklearn.model_selection  import  train_test_split
dir

<function dir>

In [41]:
feature_data,feature_test,label_data,label_test=train_test_split(iris.data,iris.target,test_size=0.20)

In [42]:
feature_data.shape

(120, 4)

In [43]:
label_data.shape

(120,)

In [44]:
feature_test.shape

(30, 4)

In [45]:
label_test.shape

(30,)

In [46]:
#  now time for calling  classifier 
from  sklearn  import  tree
clf=tree.DecisionTreeClassifier()

In [47]:
trained=clf.fit(feature_data,label_data)

In [48]:
output=trained.predict(feature_test)

In [49]:
output

array([0, 2, 1, 1, 2, 0, 0, 2, 2, 1, 2, 0, 2, 2, 1, 2, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 2])

In [50]:
label_test

array([0, 2, 1, 1, 2, 0, 0, 2, 2, 1, 2, 0, 2, 2, 1, 2, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1])